baseURL = "https://garrolan.github.io/garrosolivagant/"
languageCode = "zh-tw"
title = "GARRO的自由人生實驗室"
theme = "hugo-theme-dream"
hasCJKLanguage = true

[params]
  enableGitalk = false
  enableDarkMode = true
  description = "一個靜靜行走的記錄者"
  avatar = "images/avatar.png"
  introTitle = "GARRO的自由人生實驗室"
  introSubtitle = "探索自由人生的實驗筆記"
  favicon = "images/favicon.png"
  showSummaryCoverInPost = true
  reorderNavItems = ["lab", "tools", "search", "rss", "posts", "videos", "progress", "slides", "tags"]

  [params.navItems.lab]
    title = "關於這個實驗室"
    href = "/garrosolivagant/about/"
    target = "_self"
    icon = "information-circle"

  [params.navItems.videos]
    title = "影片"
    href = "/garrosolivagant/videos/"
    target = "_self"
    icon = "videocam"

  [params.navItems.progress]
    title = "實驗進度"
    href = "/garrosolivagant/progress/"
    target = "_self"
    icon = "stats-chart"

  [params.navItems.tools]
    title = "小工具"
    href = "/garrosolivagant/tools/"
    target = "_self"
    icon = "construct"

  [params.navItems.slides]
    title = "簡報"
    href = "/garrosolivagant/slides/"
    target = "_self"
    icon = "document-text"

[menu]
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "關於這個實驗室"
    url = "/about/"
    weight = 2
